name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      run: dotnet restore ./PresetApi/PresetApi
    - name: Build
      run: dotnet build ./PresetApi/PresetApi --configuration Release --no-restore
    - name: Test
      run: dotnet test ./PresetApi/PresetApi --no-restore --verbosity normal
    - name: Docker login
      uses: actions/docker/login@master
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Building Docker Image
      run:
          docker build --build-arg --no-cache -t Podols/PresetApi:latest .
    - name: Push Docker Container to Registry
      uses: actions/docker/cli@master
      with:
          args: push Podols/PresetApi:latest
